### ISSUE TITLE
fout bij testen met beëindigde autorisatie

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/Haal-Centraal-BRP-bevragen#1534]
Bij testen met een afnemer waar de autorisatie is beëindigd/ingetrokken (features/bevragen/autorisatie-gba.feature regel 525) heb ik de volgende Gegeven stappen:
```
Gegeven de afnemer met indicatie '000008' heeft de volgende 'autorisatie' gegevens
      | Rubrieknummer ad hoc (35.95.60) | Medium ad hoc (35.95.67) | Datum ingang (35.99.98) | Datum beëindiging tabelregel (35.99.99) |
      | 010120 010210                   | N                        | 20201128                | 20221201                                |
      En de geauthenticeerde consumer heeft de volgende 'claim' gegevens
      | naam         | waarde |
      | afnemerID    | 000008 |
      | gemeenteCode |        |
```

Hierbij geeft de automation de volgende melding:
```
....error: column "undefined" of relation "lo3_autorisatie" does not exist
    at Parser.parseErrorMessage (/Users/franksamwel/Documents/GitHub/Haal-Centraal-BRP-bevragen/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/franksamwel/Documents/GitHub/Haal-Centraal-BRP-bevragen/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/franksamwel/Documents/GitHub/Haal-Centraal-BRP-bevragen/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/franksamwel/Documents/GitHub/Haal-Centraal-BRP-bevragen/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 138,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '161',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1061',
  routine: 'checkInsertTargets'
}
no access token. authenticate
(node:19678) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
```

Waarom komt deze foutmelding? Test dit nu wel wat bedoeld was?

N.B. de API geeft wel als antwoord een 403, geen 401, dus er is blijkbaar toch een request gedaan met een token.

**Comment by MelvLee** [comment]
Geen 'Datum beëindiging tabelregel (35.99.99)' column mapping in de columnNameMap in step_defs.js vermoed ik
