### ISSUE TITLE
BRP Proxy en GBA Mock Docker containers werken niet op een M3 Pro Mac

### ISSUE THREAD

**Issue by edgarvonk** [BRP-API/Haal-Centraal-BRP-bevragen#1734]
**Beschrijf de bug**
Zowel de BRP Proxy als de GBA Mock Docker containers werken niet op een M3 Pro Mac. Wel (apart genoeg) op een M1 Mac.

**To Reproduce**
Stappen om de bug te reproduceren
1. Pull en start de BRP Proxy of de GBA Mock Docker container. In ons geval werken we met de volgende code snippets in onze Docker Compose file: 
```
  gbamock:
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-gba-mock:2.0.8
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"

  brpproxy:
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-proxy:2.1.1
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5001:5000"
    depends_on:
      - gbamock
``` 
2. De GBA Mock en BRP Proxy containers zijn niet bereikbaar op de exposed poorten. De Docker log van de brpproxy container (en idem voor de GBA Mock container) geeft de volgende error:

```
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[[TSource](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/IConfigurationBuilder%20builder,%20Action%601%20configureSource)%0A%20%20%20at%20Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder%20builder,%20IFileProvider%20provider,%20String%20path,%20Boolean%20optional,%20Boolean%20reloadOnChange)%0A%20%20%20at%20Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder%20builder,%20String%20path,%20Boolean%20optional,%20Boolean%20reloadOnChange)%0A%20%20%20at%20Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.%3C%3Ec__DisplayClass11%EE%80%860.%3CConfigureDefaults%3Eb__1(HostBuilderContext%20hostingContext,%20IConfigurationBuilder%20config)%0A%20%20%20at%20Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager%20configuration,%20HostBuilder%20innerBuilder)%0A%20%20%20at%20Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions%20options,%20Action%601%20configureDefaults)](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in /src/src/BrpProxy/Program.cs:line 16
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Verwacht gedrag**

- Beide Docker containers werken correct op een M3 Pro Mac. Waarschijnlijk is het het beste als jullie multiplatform Docker images bouwen ook voor linux/arm64.
- We hebben nu de volgende workaround (via https://stackoverflow.com/questions/76703843/system-io-ioexception-function-not-implemented-error-while-running-dotnet-doc) geïmplementeerd door de FileSystemWatcher uit te zetten. Ik vermoed dat dat sowieso beter is want wij veranderen niks aan het filesystem van deze Docker containers.
```
  gbamock:
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-gba-mock:2.0.8
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
      # Disable FileSystemWatcher because it causes this Docker container to
      # fail when running on an M3 Pro Mac with: "Unhandled exception.
      # System.IO.IOException: Function not implemented
      #   at System.IO.FileSystemWatcher.StartRaisingEvents()"
      - ASPNETCORE_hostBuilder__reloadConfigOnChange=false
    ports:
      - "5010:5010"

  brpproxy:
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-proxy:2.1.1
    platform: linux/amd64
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
      # Disable FileSystemWatcher because it causes this Docker container to
      # fail when running on an M3 Pro Mac with: "Unhandled exception.
      # System.IO.IOException: Function not implemented
      #   at System.IO.FileSystemWatcher.StartRaisingEvents()"
      - ASPNETCORE_hostBuilder__reloadConfigOnChange=false
    ports:
      - "5001:5000"
    depends_on:
      - gbamock
      ```

**Screenshots**

**Comment by CathyDingemanse** [comment]
done, fixed

**Comment by edgarvonk** [comment]
@CathyDingemanse when will this fix (and other fixes) be released in the BRP Proxy and GBA Mock Docker containers? On https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pkgs/container/haal-centraal-brp-bevragen-proxy and https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pkgs/container/haal-centraal-brp-bevragen-gba-mock I only see old versions?

**Comment by MelvLee** [comment]
Omdat de RvIG nu de BRP Proxy zelf host is het niet meer nodig dat consumers in hun eigen (productie) omgeving dat doen. Om de productie omgeving zoveel mogelijk te simuleren is een nieuwe container image '[personen-mock](https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/pkgs/container/personen-mock)' die zowel de functionaliteit van de BRP Proxy én de GBA Mock aanbiedt.
Tevens is het [test-data.json](https://raw.githubusercontent.com/BRP-API/Haal-Centraal-BRP-bevragen/master/src/config/BrpService/test-data.json) bestand dat door de personen-mock wordt gebruikt aangepast zodat het overeenkomt met de test personen uit de LAP omgeving

**Comment by CathyDingemanse** [comment]
Hi Edgar, kan ik uit jouw thumbs up reactie concluseren dat jouw probleem is opgelost?

**Comment by edgarvonk** [comment]
Dat weet ik niet @CathyDingemanse . We zijn in ieder geval van plan om binnenkort over te gaan naar die nieuwe `personen-mock` (we hadden geen idee dat die bestond tot jouw opmerking) en dan zien het wel. Hopelijk werkt die in 1x goed op de Mac ARM architectuur.

**Comment by CathyDingemanse** [comment]
Ok, ik sluit de issue niet, totdat wij van jou een teken hebben gekregen dat de overgang succesvol is geweest. Hoop snel van jullie te horen!

**Comment by CathyDingemanse** [comment]
@edgarvonk al kans gezien om te kijken of het werkt?

**Comment by edgarvonk** [comment]
Trouwens, het issue is al gesloten zo te zien?

**Comment by CathyDingemanse** [comment]
> Hoi @CathyDingemanse , nee helaas. Onze klant (Dimpact in dit geval) gaat over de prioriteit en planning van ons werk. Voorlopig staat dit nog niet op de rol. Ik vind het ook prima om dit issue te sluiten hoor. Ik maak wel een nieuwe aan mochten we nog tegen dingen aanlopen.

Ok, doen we zo!

**Comment by edgarvonk** [comment]
FYI @CathyDingemanse : we zijn eindelijk overgestapt naar de nieuwe BRP Personen mock (zowel in Docker Compose als in Kubernetes) en het werkt prima. :-) Ook geen problemen op M3 Macs.
